### PR TITLE
test: Add tests for closed stream

### LINKED ISSUE #246: test: Add `integration-test` test for `imap_next::stream::Error::Closed`
Relates to #242

### PR DESCRIPTION
**Pull request by jakoschiko**
Closes #246

### CODE REVIEW

File: integration-test/tests/client.rs [hunk 1]
```diff
@@ -431,3 +431,16 @@ fn authenticate_with_more_data_rejected() {
...
+fn stream_closed() {
+    let (rt, mut server, mut client) = TestSetup::default().setup_client();
+
+    let greeting = b"* OK ...\r\n";
+    rt.run2(server.send(greeting), client.receive_greeting(greeting));
+
+    // Close stream
+    drop(server);
+
+    rt.run(client.receive_error_because_stream_closed());
```
Comment (duesee) [inline integration-test/tests/client.rs:445]: Easy enough. Speaks for your test integration 👍🏻

**Review by duesee — APPROVED** [review]
Thanks! Also for the nice cleanup. Maybe it would have been even better to split this into two commits, cleanup + add tests. This way it would have been a bit easier to see what is important.

Should give [gumtree](https://github.com/GumTreeDiff/gumtree) another try :-)
