### PR TITLE
fix: Handle closed TLS session properly

### LINKED ISSUE #242: perf: `Stream` with TLS runs into infinite loop after connection was closed
The most inner loop in `imap_next::stream::decrypt` is the culprit. It can be tested by using the proxy and then closing the client.

Relates to #79

### PR DESCRIPTION
**Pull request by jakoschiko**
Closes #242

### CODE REVIEW

File: src/stream.rs [hunk 1]
```diff
@@ -276,15 +276,20 @@ fn decrypt(
...
+                // There are no more bytes to read
+                Err(err) if err.kind() == ErrorKind::WouldBlock => break,
+                // The TLS session was closed uncleanly
+                Err(err) if err.kind() == ErrorKind::UnexpectedEof => {
+                    return Err(DecryptEncryptError::Closed)
                 }
+                // We got an unexpected error
                 Err(err) => return Err(DecryptEncryptError::Io(err)),
+                // The TLS session was closed cleanly
+                Ok(0) => return Err(DecryptEncryptError::Closed),
```
Comment (duesee) [inline src/stream.rs:291]: Aha! Classic.

**Review by duesee — APPROVED** [review]
